import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "../assets/styles/globals.scss";
import { MainLayout } from "@/components/layout/MainLayout";

const montserrat = Montserrat({ subsets: ["latin", "cyrillic"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={montserrat.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
